language: perl
perl:
- "5.18"
- "5.16"
- "5.14"
- "5.12"
- "5.10"
- "5.08"
before_install:
- "cpanm Dist::Milla"
- "cpanm Test::More"
- "cpanm Devel::Cover::Report::Coveralls"
script:
perl Build.PL && ./Build test && cover -test -report coveralls
